name: Deploy to Yandex Cloud

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: boldrqwe/memebot:latest
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Authenticate with Yandex.Cloud
        uses: yandex-cloud/actions/auth@v0.4.0
        with:
          yc-service-account-json: ${{ secrets.YANDEX_CLOUD_SA }}
      - name: Deploy to Yandex.Cloud
        uses: yandex-cloud/actions/serverless@v0.4.0
        with:
          function: memebot
          memory: 512m
          runtime: python37
          service_account_json: ${{ secrets.YANDEX_CLOUD_SA }}
          image: boldrqwe/memebot:latest
          environment:
            db_password: ${{ secrets.DB_PASSWORD }}
            db_user_name: ${{ secrets.DB_USER_NAME }}
            bot_token: ${{ secrets.BOT_TOKEN }}
            db_host: ${{ secrets.DB_HOST }}