name: Deploy to Yandex Cloud VM

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # Temurin - a new distribution from Adoptium (previously AdoptOpenJDK)
          java-version: '17'

      - name: Install dependencies
        run: mvn clean install
      - name: Log into Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/memebot:latest
          dockerfile: Dockerfile

  deploy-to-vm:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy to Yandex.Cloud VM
        run: |
          echo "Installing Docker (if not installed)"
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "curl -fsSL https://get.docker.com | sh"

          echo "Pulling Docker image"
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "docker pull ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/memebot"

          echo "Stopping existing container (if any)"
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "docker stop memebot || true && docker rm memebot || true"

          echo "Starting new container"
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "docker run --name memebot --restart always -d -e db_password=${{ secrets.DB_PASSWORD }} -e db_user_name=${{ secrets.DB_USER_NAME }} -e bot_token=${{ secrets.BOT_TOKEN }} -e db_host=${{ secrets.DB_HOST }} ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/memebot"